
/* Drop Tables */

DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE AMOUNT CASCADE CONSTRAINTS;
DROP TABLE CONTENT CASCADE CONSTRAINTS;
DROP TABLE COMMON CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE LOCKER_REGISTRATION CASCADE CONSTRAINTS;
DROP TABLE LOCKER CASCADE CONSTRAINTS;
DROP TABLE REGISTRATION CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE SCHEDULE CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ADMIN
(
	ADMIN_CODE varchar2(2) NOT NULL,
	ADMIN_ID varchar2(20) NOT NULL UNIQUE,
	ADMIN_PASSWORD varchar2(15) NOT NULL,
	ADMIN_NAME varchar2(30),
	ADMIN_GRADE varchar2(15) NOT NULL,
	ADMIN_CHECK char(1) DEFAULT 'Y' NOT NULL,
	PRIMARY KEY (ADMIN_CODE)
);


CREATE TABLE AMOUNT
(
	AMT_CODE varchar2(2) NOT NULL,
	AMT_GRADE varchar2(25) NOT NULL,
	AMT_ITEM varchar2(15) NOT NULL,
	AMT_DAY varchar2(25) NOT NULL,
	AMT_MONTH varchar2(10) NOT NULL,
	AMT_AMOUNT varchar2(6) NOT NULL,
	PRIMARY KEY (AMT_CODE)
);


CREATE TABLE COMMON
(
	COM_CODE varchar2(2) NOT NULL,
	COM_NAME varchar2(9) NOT NULL,
	PRIMARY KEY (COM_CODE)
);


CREATE TABLE CONTENT
(
	COM_CODE varchar2(2) NOT NULL,
	CONT_DETAIL varchar2(2) NOT NULL,
	CONT_NAME varchar2(25) NOT NULL,
	CONT_RANK varchar2(2),
	PRIMARY KEY (COM_CODE, CONT_DETAIL)
);


CREATE TABLE CUSTOMER
(
	CSTMR_CODE varchar2(5) NOT NULL,
	CSTMR_ID varchar2(20) NOT NULL UNIQUE,
	CSTMR_PASSWORD varchar2(15) NOT NULL,
	CSTMR_NAME varchar2(30) NOT NULL,
	CSTMR_ADRES varchar2(80) NOT NULL,
	CSTMR_MAIL varchar2(40) NOT NULL UNIQUE,
	CSTMR_PHONE varchar2(13) NOT NULL,
	CSTMR_BRTHDY varchar2(8) NOT NULL,
	CSTMR_SEXDSTN varchar2(6) NOT NULL,
	ADMIN_CHECK char(1) DEFAULT 'N' NOT NULL,
	PRIMARY KEY (CSTMR_CODE)
);


CREATE TABLE LOCKER
(
	LOC_NO varchar2(3) NOT NULL,
	LOC_USE char(1) DEFAULT 'N' NOT NULL,
	PRIMARY KEY (LOC_NO)
);


CREATE TABLE LOCKER_REGISTRATION
(
	LOC_NO varchar2(3) NOT NULL,
	LR_REGDATE varchar2(8) NOT NULL,
	MBER_CODE varchar2(7) NOT NULL,
	LR_STR varchar2(8) NOT NULL,
	LR_END varchar2(8) NOT NULL,
	PRIMARY KEY (LOC_NO, LR_REGDATE)
);


CREATE TABLE MEMBER
(
	MBER_CODE varchar2(7) NOT NULL,
	MBER_NM varchar2(30) NOT NULL,
	MBER_GRADE varchar2(25) NOT NULL,
	MBER_PHONE varchar2(13) NOT NULL,
	MBER_BRTHDY varchar2(6) NOT NULL,
	MBER_SEXDSTN varchar2(6) NOT NULL,
	MBER_NOTE varchar2(150),
	PRIMARY KEY (MBER_CODE)
);


CREATE TABLE REGISTRATION
(
	MBER_CODE varchar2(7) NOT NULL,
	REGIST_REGDATE varchar2(8) NOT NULL,
	SCH_CODE varchar2(2) NOT NULL,
	REGIST_STATE varchar2(9) NOT NULL,
	REGIST_STR varchar2(8) NOT NULL,
	REGIST_END varchar2(8) NOT NULL,
	REGIST_MONTH varchar2(7) NOT NULL,
	REGIST_AMOUNT varchar2(7) NOT NULL,
	REGIST_NOTE varchar2(150),
	REGIST_REFND char(1) DEFAULT 'N' NOT NULL,
	REGIST_REFNDDATE varchar2(8),
	PRIMARY KEY (MBER_CODE, REGIST_REGDATE)
);


CREATE TABLE SCHEDULE
(
	SCH_CODE varchar2(2) NOT NULL,
	SCH_ITEM varchar2(15) NOT NULL,
	SCH_CLASS varchar2(15) NOT NULL,
	SCH_TIME varchar2(11) NOT NULL,
	SCH_DAY varchar2(25) NOT NULL,
	SCH_PSNCPA varchar2(2) NOT NULL,
	SCH_OPEN char(1) DEFAULT 'Y' NOT NULL,
	PRIMARY KEY (SCH_CODE)
);



/* Create Foreign Keys */

ALTER TABLE CONTENT
	ADD FOREIGN KEY (COM_CODE)
	REFERENCES COMMON (COM_CODE)
;


ALTER TABLE LOCKER_REGISTRATION
	ADD FOREIGN KEY (LOC_NO)
	REFERENCES LOCKER (LOC_NO)
;


ALTER TABLE LOCKER_REGISTRATION
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MEMBER (MBER_CODE)
;


ALTER TABLE REGISTRATION
	ADD FOREIGN KEY (MBER_CODE)
	REFERENCES MEMBER (MBER_CODE)
;


ALTER TABLE REGISTRATION
	ADD FOREIGN KEY (SCH_CODE)
	REFERENCES SCHEDULE (SCH_CODE)
;



